services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    volumes:
      - ./01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./02_insert_test_data.sql:/docker-entrypoint-initdb.d/02_insert_test_data.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8090:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

networks:
  default:
    name: local-network
    external: true